### PR TITLE
fix(caldav): restore CalDAV backend compatibility with the new Task core API

### PR DESCRIPTION
**Pull request by pentux-GitHub**
## Summary

The CalDAV backend was written against the old GTG core API, where `Task` 
exposed a set of getter/setter methods (`get_title()`, `set_due_date()`, 
`get_uuid()`, etc.). Following the core rewrite, `Task` now exposes these 
values as Python properties (`task.title`, `task.date_due`, `task.id`, etc.).

This PR restores full compatibility between the CalDAV backend and the new 
core, fixing a cascade of errors that prevented the backend from syncing at 
all.

---

## Errors fixed

**`backend_caldav.py`**

| Error | Root cause | Fix |
|---|---|---|
| `TypeError: 'str' object is not callable` | `Field.get_gtg()` and `write_gtg()` called old getter/setter methods that no longer exist as callables | Added `PROPERTY_GET_MAP` and `PROPERTY_SET_MAP` dictionaries to bridge old method names to new property access |
| `KeyError` on task lookup | `tasks.lookup[uid]` raises if key is absent | Changed to `tasks.lookup.get(UUID(uid))` |
| `TypeError: Task.__init__() missing arguments` | `Task()` now requires `id` and `title` | Changed to `Task(id=UUID(uid), title='')` |
| `AttributeError: 'set' object has no attribute 'sort'` | `task.tags` is now a `set`, not a list | Removed `task.tags.sort()`, which has no meaning on a set |
| `NameError: name 'uid' is not defined` in `_get_calendar_tasks` | `uid` was referenced but never defined in this scope (broken since commit 74bd3f44, see #1176) | Changed to `str(task.id)` |
| `KeyError` in `set_task` | `datastore.tasks.add()` raises if task already exists | Added a guard: only call `add()` if task is not already in the store |

**`generic_backend.py`**

| Error | Root cause | Fix |
|---|---|---|
| `AttributeError: 'UUID' object has no attribute 'get_id'` | `datastore` now passes `task.id` (a UUID) to `queue_set_task()`, but the method tried to call `.get_id()` on it | Refactored `queue_set_task()` and `launch_setting_thread()` to work with UUID directly, resolving the Task object from the store before calling `set_task()` |

---

## Behavior after this fix

- CalDAV backend connects and syncs successfully ✅
- Tasks from the remote CalDAV server are imported into GTG ✅  
- Terminal is clean — no exceptions during normal sync operation ✅

## Known remaining issue

Tasks created in GTG are not yet pushed back to the CalDAV server. 
This appears to be a separate issue in the outbound sync path and is 
not introduced by this PR.

## Testing

Tested against a live Nextcloud CalDAV server. Tasks created remotely 
are correctly imported into GTG on the next sync cycle.

### CODE REVIEW

**Comment by pentux-GitHub** [comment]
Update: after further testing, the fix also restores the GTG → CalDAV 
sync direction (tasks created in GTG are now pushed to the remote server).

Two additional fixes were needed beyond the initial commit:

1. `datastore.py`: connect `task-filterably-changed` signal to 
   `queue_set_task()` so backends are notified when a task is modified.
   Without this, changes in GTG were never pushed to the backend.

2. `backend_caldav.py`: replace remaining old-API calls 
   (`get_added_date()`, `get_subtasks()`, `Task.STA_ACTIVE`, 
   `tasks.remove(str)`) with new core equivalents.

Tested: tasks created in GTG with the correct CalDAV calendar tag 
(`@DAV_Personnel` in my case) are now correctly pushed to the 
Nextcloud CalDAV server.

**Comment by diegogangl** [comment]
Testing this. I came across this error when sync-ing:

```
Exception in thread Thread-1 (__backend_startup):
Traceback (most recent call last):
  File "/usr/lib64/python3.14/threading.py", line 1082, in _bootstrap_inner
    self._context.run(self.run)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib64/python3.14/threading.py", line 1024, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/datastore.py", line 646, in __backend_startup
    backend.start_get_tasks()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/interruptible.py", line 38, in new
    return fn(*args)
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/periodic_import_backend.py", line 79, in start_get_tasks
    self._start_get_tasks()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/periodic_import_backend.py", line 98, in _start_get_tasks
    self.do_periodic_import()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/interruptible.py", line 38, in new
    return fn(*args)
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/backend_caldav.py", line 112, in do_periodic_import
    self._do_periodic_import()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/backend_caldav.py", line 148, in _do_periodic_import
    self._import_calendar_todos(calendar, start, counts)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/backend_caldav.py", line 299, in _import_calendar_todos
    for todo in self.__sort_todos(todos):
                ~~~~~~~~~~~~~~~~~^^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/backend_caldav.py", line 339, in __sort_todos
    or self.datastore.tasks.lookup.get(UUID(uid))):  # already known uid
                                       ~~~~^^^^^
  File "/usr/lib64/python3.14/uuid.py", line 219, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string

```

**Comment by pentux-GitHub** [comment]
Thanks a lot for testing! That's a real gap in my fix: I assumed CalDAV UIDs
are always valid UUIDs. My Nextcloud generates UUID-shaped UIDs so I never
hit it, but the spec only requires a unique string, so `UUID(uid)` can crash
on other servers or clients like yours.

I'll rebase the branch (it now conflicts with #1264 which got merged), add a
proper guard for non-UUID UIDs, re-test against Nextcloud in both directions,
and ping you here.

**Comment by pentux-GitHub** [comment]
Rebased on current master (the conflict was with my own #1264, which this
branch's refactor supersedes), and fixed the crash you found. Thanks again
for testing, your server caught what mine couldn't!

## Root cause of your ValueError

My fix assumed CalDAV UIDs are always valid UUIDs. My Nextcloud generates
UUID-shaped UIDs so I never hit it, but RFC 5545 only requires an opaque
unique string, which is what your server produces.

## Fix

New `uid_to_task_id()` helper: a valid UUID string is used as-is, anything
else is mapped to a stable name-based UUID (RFC 4122 uuid5), so the same
remote UID always yields the same task id across sync runs. It is applied
at every boundary between remote UIDs and the GTG task store: the import
loop, the `__sort_todos` lookup that crashed for you, the cache keys, and
the reconciliation set.

Canonicalizing the cache keys and the reconciliation set also fixes a
latent bug for valid-but-non-canonical UUIDs (e.g. uppercase, which
Nextcloud's own web UI produces): without it, such tasks were flagged
"missing from backend" on every cycle (delete + reimport churn) and pushes
could create duplicates. I caught one live during testing: an
uppercase-UID todo now updates in place.

Also removed the last old-core API call left in the file
(`task.req.get_task()` in `_extract_plain_text`), which crashed when
pushing any task whose content references subtasks (the tutorial task
does).

## Tests

Added a new, unskipped test class with 3 tests: importing a non-UUID UID
(reproduces your exact ValueError on master), mapping stability, and the
subtask-reference extraction. The old skipped suite still targets the
pre-rewrite core API; modernizing it is a separate follow-up I'd be happy
to tackle.

Re-tested against a live Nextcloud in both directions, including cross
modifications updating the same .ics file (no duplicates).

## Known limitation (for a follow-up)

For non-UUID-UID servers, `_clean_task_missing_from_backend` queries the
server by the GTG task id (`todo_by_uid`), which can't match the original
remote UID, so the graceful "fetch and update" recovery degrades to
delete + reimport on the next cycle. The proper fix is storing the remote
UID as a namespaced task attribute (the backend already does this for
calendar name/url); that felt out of scope here.

Could you give it another run against your server?

**Comment by diegogangl** [comment]
It's moving along now, I'm getting this error (through the gui):


```python-traceback
Traceback (most recent call last):
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/gtk/browser/main_window.py", line 1725, in remove_backend_infobar
    self.vbox_toolbars.foreach(self.__remove_backend_infobar, backend_id)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Box' object has no attribute 'foreach'
```
and I'm seeing this in the command line:

```
Traceback (most recent call last):
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/tasks.py", line 807, in _model_expand
    self.tid_to_subtask_model[item.id] = self._create_model_for_children(item)
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/tasks.py", line 815, in _create_model_for_children
    if self.task_filter.match(child):
       ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
TypeError: argument item: Expected GObject.Object, but got str
Traceback (most recent call last):
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/gtk/browser/task_pane.py", line 507, in <lambda>
    ,lambda _,x: not self.filter_manager.has_matching_children(item)),
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/tasks.py", line 709, in has_matching_children
    return any(self.task_filter.match(c) for c in task.children)
           ^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/tasks.py", line 709, in <genexpr>
    return any(self.task_filter.match(c) for c in task.children)
               ~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: argument item: Expected GObject.Object, but got str
Traceback (most recent call last):
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/filters.py", line 141, in do_match
    return (self.is_task_matched_by_pane(task)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/filters.py", line 121, in is_task_matched_by_pane
    return task.is_actionable
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.14/site-packages/gi/_propertyhelper.py", line 246, in __get__
    value = self.fget(instance)
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/tasks.py", line 123, in is_actionable
    active_children = all(t.status != Status.ACTIVE for t in self.children)
                      ^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/tasks.py", line 123, in <genexpr>
    active_children = all(t.status != Status.ACTIVE for t in self.children)
                          ^^^^^^^^
AttributeError: 'str' object has no attribute 'status'
```

**Comment by pentux-GitHub** [comment]
Second layer peeled! Reproduced your `str`-in-`task.children` with the
project's own RELATED-TO fixtures (`UID:ROOT` / `UID:CHILD`): the generic
field pipeline was feeding raw UID strings to `Task.add_child()`, which
appends anything without a type check. The same pattern sat one layer
deeper for CATEGORIES: `task.add_tag()` was given plain strings, which the
new core rightfully refuses, so any todo with categories crashed the
import too.

Fix, in the last commit:
- `fill_task` no longer routes CATEGORIES / RELATED-TO through the generic
  string pipeline; categories become real Tag objects via
  `datastore.tags.new()`, keeping the same add/remove diff logic.
- Hierarchy is wired explicitly in the import loop with the store API
  (`datastore.tasks.parent()`), relying on `__sort_todos` importing
  parents first. Conservative on purpose: links are only created, never
  re-parented nor removed from the DAV side.

Two more regression tests (parent/child import, categories import), suite
at 5 passing. Re-validated against a live Nextcloud: a real parent with
two subtasks and tagged todos land as real Task/Tag objects, zero
anomalies, and the hierarchy renders correctly in the browser.

Unrelated heads-up while testing: task store mutations from the sync
thread occasionally froze or crashed the UI (GLib ref-count assertion),
independently of this branch's changes. I have a mechanism map and will
file it as a separate core issue rather than widen this PR.

Another run on your side would be gold. If a third layer shows up, send
it over, this onion is getting peeled either way.

**Comment by diegogangl** [comment]
Seems like this is blocked by #1241

**Comment by pentux-GitHub** [comment]
Unblocked: the infobar port discussed in #1241 is up as #1284 (replace
with the number) — with it, backend errors show a banner instead of
freezing, so this PR can be re-tested.

**Comment by pentux-GitHub** [comment]
Pushed an additional commit that fixes a CalDAV sync loop I hit while
testing this backend against a real Nextcloud task calendar: `SEQUENCE`
was bumped on every `_set_task`, even when `should_sync()` reported no
change, so each imported remote edit echoed back a higher `SEQUENCE` and
the same todos were rewritten on every cycle. The increment now happens
only when a real change is actually saved (RFC 5545 semantics).

Full analysis and reproduction in #1290. Verified against Nextcloud: an
unchanged task keeps a stable `SEQUENCE` and the loop is gone.

Happy to split this into its own PR if you'd rather review it
separately, but since the CalDAV backend only runs with this PR applied,
it seemed most useful to include it here.

**Comment by diegogangl** [comment]
It seemed to work the first time, but afterwards GTG crashes on startup with the following:

```
Traceback (most recent call last):
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/gtk/application.py", line 121, in do_startup
    self.ds.find_and_load_file(data_file)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/datastore.py", line 478, in find_and_load_file
    self.load_file(filepath)
    ~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/datastore.py", line 212, in load_file
    self.load_data(self.xml_tree)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/datastore.py", line 194, in load_data
    self.tasks.from_xml(tasks_xml, self.tags)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/tasks.py", line 917, in from_xml
    assert added_element.text is not None, 'Added text not found in task '+str(tid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Added text not found in task 945ff268-6976-5b56-9824-68ada97d91ec
Gtk-Message: 09:52:28.885: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/gtk/application.py", line 161, in do_activate
    if self._check_exception():
       ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/gtk/application.py", line 216, in _check_exception
    dialog.set_application(self)  # Keep application alive, for now
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_application'
Traceback (most recent call last):
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/gtk/application.py", line 672, in do_shutdown
    self.ds.save()
    ~~~~~~~~~~~~^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/datastore.py", line 250, in save
    assert path is not None, "Failed to determine save location."
           ^^^^^^^^^^^^^^^^
AssertionError: Failed to determine save location.

(gtg:679816): GLib-GIO-CRITICAL **: 09:52:28.916: GApplication subclass 'GTG+gtk+application+Application' failed to chain up on ::shutdown (from end of override function)

```

**Comment by pentux-GitHub** [comment]
Thanks, that's a real bug and the traceback has everything needed —
reproduced and fixed in the last commit.

What happens: `CREATED` is optional in RFC 5545, and the field is in
`DateField`'s ignored-values list, so a VTODO without it never writes
to the task. The task therefore keeps the `Date.no_date()` it gets
from `Task()`. `str(Date.no_date())` is the empty string, so `to_xml`
writes `<added></added>`, lxml reads that back as `None`, and the
assert at tasks.py:917 aborts the whole load. Hence "worked the first
time, crashes afterwards": the damage is done at save time.

The fix gives imported tasks a fallback added date. I used
`date_modified` rather than `now()` on purpose: `now()` would claim
the task was created during the import, whereas LAST-MODIFIED is
always set and is a truthful upper bound. New test
`test_import_todo_without_created_date` fails on the previous commit,
passes on this one.

One thing this does *not* fix: your current file is already written
with an empty `<added>`, so it will still refuse to load. To recover
it:

(back up the file first, obviously)

    python3 - <<'EOF'
    from lxml import etree
    path = 'gtg_data.xml'   # adjust
    tree = etree.parse(path)
    fixed = 0
    for dates in tree.iter('dates'):
        added, modified = dates.find('added'), dates.find('modified')
        if added is not None and not added.text \
                and modified is not None and modified.text:
            added.text = modified.text
            fixed += 1
    tree.write(path, encoding='UTF-8', xml_declaration=True)
    print(fixed, 'tasks repaired')
    EOF

That leads to the wider point: the core currently writes a file it
then refuses to read. A task with no added date is serializable but
not loadable, and the assert takes the entire database down rather
than the one task. That's the same family as #1289, and probably
deserves its own fix in `from_xml` — happy to take it on separately if
you think that shape is right.

**Comment by pentux-GitHub** [comment]
Following up on my own comment: I found your #1240 ("Ensure we have an
added date to task in caldav", July 2025) — same diagnosis, a year
before mine. It does exactly the right thing:

    if not task.get_added_date():
        task.set_added_date(datetime.now())

It just predates the core rewrite: `get_added_date()` /
`set_added_date()` are gone from `Task`, so it would `AttributeError`
on current master. That's presumably why it stayed open.

So I've moved my guard to your spot — end of `fill_task`, right after
the calendar tag — instead of the import loop. Same place, new API,
and it now also covers `_update_task`, which goes through `fill_task`
too. The only thing I did differently is falling back on
`date_modified` rather than `now()`: `now()` would date the task from
the import rather than from its actual life. Force-pushed as an amend
since the commit was minutes old.

That should make #1240 redundant — but it's your patch and your call,
so tell me if you'd rather keep yours and I'll drop mine.

Test `test_import_todo_without_created_date` still red before / green
after. Full local suite green, CI green, no conflicts with master.

**Comment by diegogangl** [comment]
This is almost there!

I found 3 problems:

1. Some tasks have tags like this: `@DAV_Deck:_Server`. The `:` are not recognized as part of tags, so maybe they should be replaced by something else? 

2. Opening a task with these tags makes it so that everytime I open the task the tag is added again

3. Subtasks are syncronized from ths server, but not _to_ the server

4. I found this traceback in the terminal

```
2026-07-16 10:36:23,948 - ERROR - backend_caldav:_set_task:203 - Something went wrong while updating Task "List : Metrics" with id "55662985-81ea-52f8-a309-7f2c4e482361".Status: Status.ACTIVE, tags: DAV_Deck:_Server, DAV_Deck => Todo([REDACTED URL].ics)
Traceback (most recent call last):
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/backend_caldav.py", line 201, in _set_task
    todo.save()
    ~~~~~~~~~^^
  File "/home/januz/.local/lib/python3.14/site-packages/caldav/calendarobjectresource.py", line 1163, in save
    self._create(id=self.id, path=path)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/januz/.local/lib/python3.14/site-packages/caldav/calendarobjectresource.py", line 1004, in _create
    self._put()
    ~~~~~~~~~^^
  File "/home/januz/.local/lib/python3.14/site-packages/caldav/calendarobjectresource.py", line 975, in _put
    return self._put(False)
           ~~~~~~~~~^^^^^^^
  File "/home/januz/.local/lib/python3.14/site-packages/caldav/calendarobjectresource.py", line 977, in _put
    raise error.PutError(errmsg(r))
caldav.lib.error.PutError: PutError at '404 Not Found

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Node with name 'stack-13.ics' could not be found</s:message>
</d:error>
', reason no reason
```

**Comment by pentux-GitHub** [comment]
All four turned out to be real, and two had causes I had completely
missed. Rebased on current master (so #1284 is in: backend errors now
show a banner instead of tracebacks) and pushed four separate commits,
one per cause, so you can take, drop or reorder them independently.

**1 & 2 — tags with `:` — `only build tags the core can parse back`**

One bug. `to_tag()` only replaced spaces, so "Deck: Server" produced
`DAV_Deck:_Server`. GTG's tag parsers don't agree on what a tag may
contain: `core.tags` accepts `:`, while the editor's `TAG_REGEX` and
`core.tasks`' `TAG_LINE_REGEX` stop at anything outside `\w` and `-`.
So the editor read back `@DAV_Deck`, truncated, and re-added it as a
second tag on every open — exactly what you saw. The backend now only
builds tags every parser agrees on. (The parsers disagreeing is a core
issue of its own; I didn't want to widen this PR with it.)

**3 — subtasks not going up — two commits, two causes**

- `port the sort-order field to the new core API`: `OrderField` called
  `parent.get_child_index(uid)`, removed by the rewrite, so **every**
  push of a subtask raised AttributeError. That alone explains "from
  the server but not to the server".
- `send the server's own UID in RELATED-TO`: `get_parents` returned
  `str(task.parent.id)` — for a server whose UIDs aren't UUIDs, that's
  the uuid5 *I* derived from the UID, a value the server never issued,
  so it drops the link. The remote UID is now kept as a task attribute
  at import and used in RELATED-TO. This also closes the "known
  limitation" I flagged earlier about `_clean_task_missing_from_backend`.

**A fourth one you didn't report, found while testing this**

`let a rename reach the backends and the filters`: renaming a task
emitted no signal at all. `TaskStore.add()` only wires
`notify::is-actionable`, `notify::is-active` and `tags-changed` to
`task-filterably-changed` — the title, which is also what search
filters on, was missing. So the server kept whatever title the task
had when some other signal last fired: my subtasks reached Nextcloud
named "so", "sou" and "s", the first letters I had typed. This one is
in the core rather than the backend; it's the only reason the sync
looks right now. No storm of pushes either: the editor already
debounces its saves (`GnomeConfig.SAVETIME`).

**4 — the PutError**

Consequence rather than cause, I think. The failing task ("List :
Metrics") carried both `DAV_Deck:_Server` and the phantom `DAV_Deck`;
the truncated tag matched no calendar, so the backend fell back to the
default one and Deck refused. With the tag fixed it should resolve to
its own calendar and stop being marked modified on every open. If Deck
still refuses a genuine edit, that's a read-only remote and GTG can
only log it — which it does. I get the same class of refusal here on a
share I can't write to; #1291 is about that noise.

**Verified live against Nextcloud**: a parent, two subtasks and a
grand-child created in GTG now appear correctly nested on the server,
with full titles, tags and dates. 236 tests passing locally, CI green,
each commit red before / green after.

Still open, for later: only a title change notifies backends — editing
just the body of a task doesn't (`content` isn't a GObject property).
Worth its own fix, out of scope here.

If four commits at once is too much to take, rolling back to `always
give imported tasks an added date` and merging that as a baseline is a
perfectly reasonable call — I'd reopen the rest as its own PR. Your
repo, your rhythm.

**Comment by diegogangl** [comment]
Almost everything works. Tested with a task that a subtask which also had a subtask. The middle subtask got a tag in the title (`@DAV_Personal`) and the content of the root task was broken.
Also we get the tag repeating every time I open the task. And "Otra subtask" is also repeated using markdown syntax

```Una nueva task para sync
Let's see how it takes sync, @DAV_Personal, @DAV_Personal

[ ] Otra subtask
[ ] Otra subtask
Otra subtask

```

**Comment by diegogangl** [comment]
I also got a traceback here:

```
Exception in thread Thread-1 (__backend_startup):
Traceback (most recent call last):
  File "/usr/lib64/python3.14/threading.py", line 1082, in _bootstrap_inner
    self._context.run(self.run)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/lib64/python3.14/threading.py", line 1024, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/datastore.py", line 703, in __backend_startup
    backend.start_get_tasks()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/interruptible.py", line 38, in new
    return fn(*args)
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/periodic_import_backend.py", line 79, in start_get_tasks
    self._start_get_tasks()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/periodic_import_backend.py", line 98, in _start_get_tasks
    self.do_periodic_import()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/core/interruptible.py", line 38, in new
    return fn(*args)
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/backend_caldav.py", line 114, in do_periodic_import
    self._do_periodic_import()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/backend_caldav.py", line 148, in _do_periodic_import
    self._import_calendar_todos(calendar, start, counts)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/backend_caldav.py", line 292, in _import_calendar_todos
    calendar_tasks = dict(self._get_calendar_tasks(calendar))
  File "/home/januz/code/gtg/.local_build/install/lib/python3.14/site-packages/GTG/backends/backend_caldav.py", line 352, in _get_calendar_tasks
    yield uid, task # noqa: F821
          ^^^
NameError: name 'uid' is not defined. Did you mean: 'id'?

```

**Comment by pentux-GitHub** [comment]
Thanks for the new round! Before anything else: the traceback in your
last comment can't come from this branch. The line it quotes,
`yield uid, task  # noqa: F821`, only exists on master (the noqa was
added there in Jan 2025); this branch rewrote that line in its very
first commit (now `yield str(task.id), task`, line 407). The line
numbers agree: backend_caldav.py:352 and datastore.py:703 are current
master, and :703 only shifted to that position with today's #1293
merge. The branch itself hasn't moved since my last push (76ff3b3).

So for the crash: checking out fix/caldav-new-core-compat and
rebuilding should make it disappear, since it's literally the #1176
bug this branch fixes.

For the content damage in your previous comment: since it's most
likely the same build, I can't tell residue from regression yet. Your
data file and the Nextcloud calendar also carry scars from the earlier
rounds (including the truncated-tag era). A clean pass would be:
branch checked out, rebuilt, and ideally a fresh data file, otherwise
we're measuring the wreckage of past tests.

One thing I'm not waving away: `@DAV_Personal` has no character the
tag parsers disagree on, so if the re-tagging on open still happens on
the branch with clean data, my truncation explanation from the 16th
doesn't cover it. I'm reading the editor side of that right now either
way, and I'll report here.

**Comment by pentux-GitHub** [comment]
Update on the re-tagging, as promised: it's explained, and it's not this
branch. It's a pre-existing race in the editor, on master.

Short chain: `Task.add_tag()` (tasks.py:303) puts the tag in the task's
set but never touches the content. On every editor open,
`set_text_from_task` (taskview.py:166) re-inserts all the task's tags
into the text. Its "already in the buffer" guard checks `task_tags`,
which is only filled by `process()` on a 250 ms timer, so at open time
it checks an empty set and filters nothing. `get_text()` then saves the
duplicate. One more copy per open/close cycle.

CalDAV is just the main way tags reach the model without being typed, so
you'll still see the re-tagging after checking out this branch: it's not
a signal against the PR. I'll file it as its own core issue.

The duplicated subtasks: I suspect the same family
(`set_text_from_task` also re-inserts model subtasks it didn't detect in
the text, lines 188-192), but the full mechanism depends on what earlier
pushes wrote into the DESCRIPTION, so that part is not established and
I'm not claiming it. I need time to dig, and I'll be less available over
the coming days, so it may take a little while. The re-test on the
branch with fresh data is still the most useful next step meanwhile.

**Comment by pentux-GitHub** [comment]
One scope note before your next test pass, so expectations are right: **this PR does not cover pushing local deletions to the server.**

While re-reviewing the branch I traced the removal path: nothing ever calls `queue_remove_task`, so deleting a task in GTG never reaches the DAV server. Predicted symptom (stated, not yet tested): a locally deleted task should reappear at the next periodic import. This is not a regression — current master pushes nothing at all, deletions included — but I'd rather state it explicitly than have you find it mid-test.

I'd propose keeping it out of this PR, which is about restoring compatibility, and wiring the deletion path in a follow-up: it needs the datastore's removal signal connected to `queue_remove_task`, plus the backend's `remove_task`/`_remove_task` pair sorted out (right now the public one touches the local store and the DAV delete has no caller). That deserves its own focused review. If you'd rather have it fixed in this PR before merging, I can do that instead — your call.

**Comment by diegogangl** [comment]
Fair enough. This PR is getting a bit long to review too. I will merge this one for now (since it LGTM)
