### ISSUE TITLE
Traceback when dragging a task to a tag in the sidebar (liblarch bug)

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#269]
One way to add a tag to one (or multiple) tasks is to drag them to a tag in the sidebar. This works in 0.3.x, but is broken in the git version, giving this traceback:

```
Traceback (most recent call last):
  File "/home/jeff/gtg/src/liblarch/liblarch_gtk/__init__.py", line 523, in on_drag_data_received
    src_model = context.get_source_widget().get_model()
AttributeError: 'X11DragContext' object has no attribute 'get_source_widget'
```

This was tested in the X11/Xorg version of GNOME on Ubuntu 20.04, so not a Wayland issue per se, but we should make sure it works on Wayland too.

Hesitating whether to target this to 0.4 or 0.5, and whether this is critical or high or medium priority. I'm guessing medium because it's a traceback that happens in the specific case of dragging to the sidebar (which is not shown by default) and that feature may not be the most used one, but a traceback is a traceback and it should "not happen". So if we can somehow get it fixed easily-enough for 0.4 that's great, otherwise I guess it's not the end of the world.

**Comment by diegogangl** [comment]
I don't think this would be hard but I'm not sure how to setup liblarch so that gtg uses it on my machine. @ploum do you remember how to set this up?

**Comment by ploum** [comment]
simply put the liblarch git on the same level of the gtg git repository. Then, I don't remember if it's automatic or if there's some command to launch it. It has been changed after I left the project but @nekohayo could help.

**Comment by diegogangl** [comment]
So, looks like the DnD changed at some point to accommodate Wayland and that broke it in liblarch. It's going to be quite some work updating it, and on top of that the whole system has been redesigned from scratch for Gtk4. And on top of that, if we switch to listboxes we might not even use that treeview widget anymore. So I've disabled DnD for now.

**Comment by nekohayo** [comment]
I just realized that your commit in liblarch does not only disable dragging to the tasks sidebar, it breaks the ability to change the hierarchy of subtasks by dragging _within_ the tasks browser view, which was working fine without tracebacks.

I'd rather have the tags traceback (and ideally we find the correct fix eventually…) instead of losing the other feature by throwing out drag & drop support entirely.

So I'd recommend reverting https://github.com/getting-things-gnome/liblarch/commit/b5d46b38 ; I'm not even sure it's a bug in liblarch rather than just something silly that GTG forgot to do.

I mean, if it works within one treeview, just not "from that treeview to the other", is it really an impossible bug? The traceback makes it sound like it's just some silly variable/object name reference that got lost somewhere.

>  if we switch to listboxes we might not even use that treeview widget anymore. 

Not sure why we should do that, now that I think of it... because then you no longer have the ability to hierarchically represent tasks like what we have right now when you show all open tasks? Overall being able to move tasks across different levels of hierarchy (i.e. parent/deparent subtasks) is useful in my humble opinion.

**Comment by diegogangl** [comment]
> The traceback makes it sound like it's just some silly variable/object name reference that got lost somewhere.

The dnd system changed in Gtk, the function that's causing the traceback doesn't exist anymore. There's no documentation or obvious way to replace it as far as I could find.
Not sure why it would work for one tree to the other. Maybe it's going through a different if-path.

I reverted the commit

> if we switch to listboxes we might not even use that treeview widget anymore.
> 
> Not sure why we should do that, now that I think of it... because then you'd no longer have the ability to hierarchically represent tasks like what we have right now when you show all open tasks? Overall being able to move tasks across different levels of hierarchy (i.e. parent/deparent subtasks) is useful in my humble opinion.

You can still have a hierarchy with listboxes since you can have any layout and widgets you want inside a listrow.

**Comment by nekohayo** [comment]
I have now fixed it in https://github.com/getting-things-gnome/liblarch/commit/59de1f3c4b
All the drag & drop features now work. Peace has been restored.

For those following along at home, you will have to either manually update the liblarch checkout in gtg's "src" folder, or rerun `pip3 install -r requirements.txt` before launching gtg.sh
